# Generated by Django 3.2.7 on 2021-10-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, unique=True, verbose_name='город')),
                ('address', models.TextField(verbose_name='адрес')),
                ('telephone', models.CharField(max_length=11, verbose_name='телефон')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
            ],
        ),
    ]
