# Generated by Django 3.2.7 on 2021-10-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_alter_contacts_telephone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
